export const employees = [
    {
      id: 1,
      name: 'John Doe',
      description: 'Software Engineer',
      email: 'john.doe@example.com',
      image: 'https://randomuser.me/api/portraits/men/1.jpg',
      manager: 'Jane Smith',
      seniority: 'Mid-level',
      address: '123 Main Street, Anytown USA',
      latitude: 37.7749,
      longitude: -122.4194,
      phone: '123-456-7890',
      interests: 'Coding, Traveling, Hiking',
      birthdate: '1985-06-15'
    },
    {
      id: 2,
      name: 'Jane Smith',
      description: 'Marketing Manager',
      email: 'jane.smith@example.com',
      image: 'https://randomuser.me/api/portraits/women/1.jpg',
      manager: 'Michael Johnson',
      seniority: 'Executive',
      address: '456 Oak Avenue, Othertown USA',
      latitude: 34.0522,
      longitude: -118.2437,
      phone: '234-567-8901',
      interests: 'Digital Marketing, Reading, Yoga',
      birthdate: '1980-03-22'
    },
    {
      id: 3,
      name: 'Michael Johnson',
      description: 'HR Specialist',
      email: 'michael.johnson@example.com',
      image: 'https://randomuser.me/api/portraits/men/2.jpg',
      manager: null,
      seniority: 'Manager',
      address: '789 Elm Street, Elsewhere USA',
      latitude: 42.3601,
      longitude: -71.0589,
      phone: '345-678-9012',
      interests: 'Recruitment, Coaching, Sports',
      birthdate: '1990-01-10'
    },
    {
      id: 4,
      name: 'Alice Williams',
      description: 'Product Designer',
      email: 'alice.williams@example.com',
      image: 'https://randomuser.me/api/portraits/women/2.jpg',
      manager: 'Jane Smith',
      seniority: 'Senior',
      address: '123 Birch Street, Newtown USA',
      latitude: 40.7128,
      longitude: -74.0060,
      phone: '456-789-0123',
      interests: 'UI/UX Design, Photography, Painting',
      birthdate: '1992-07-29'
    },
    {
      id: 5,
      name: 'David Brown',
      description: 'Software Architect',
      email: 'david.brown@example.com',
      image: 'https://randomuser.me/api/portraits/men/3.jpg',
      manager: 'Michael Johnson',
      seniority: 'Lead',
      address: '101 Pine Street, Hometown USA',
      latitude: 51.5074,
      longitude: -0.1278,
      phone: '567-890-1234',
      interests: 'System Architecture, AI, Chess',
      birthdate: '1983-09-17'
    },
    {
      id: 6,
      name: 'Sophia Davis',
      description: 'Data Scientist',
      email: 'sophia.davis@example.com',
      image: 'https://randomuser.me/api/portraits/women/3.jpg',
      manager: 'Michael Johnson',
      seniority: 'Junior',
      address: '202 Maple Avenue, Uptown USA',
      latitude: 37.7749,
      longitude: -122.4194,
      phone: '678-901-2345',
      interests: 'Machine Learning, Reading, Traveling',
      birthdate: '1995-11-05'
    }
  ];
  